# syntax version.
version: "3.7"

# services list.
services:
  # base image
  alpine-base:
    image: "hyperf/hyperf:8.1-alpine-v3.18-base"
    build:
      context: "8.1/alpine/base"
      args:
        ALPINE_VERSION: "3.18"

  # swoole image
  alpine-swoole:
    image: "hyperf/hyperf:8.1-alpine-v3.18-swoole"
    build:
      context: "8.1/alpine/swoole"
      args:
        ALPINE_VERSION: "3.18"
        SW_VERSION: "swoole"
        COMPOSER_VERSION: "COMPOSER_VERSION_VALUE"
        PHP_BUILD_VERSION: "PHP_BUILD_VERSION_VALUE"

  # swow image
  alpine-swow:
    image: "hyperf/hyperf:8.1-alpine-v3.18-swow"
    build:
      context: "8.1/alpine/swow"
      args:
        ALPINE_VERSION: "3.18"
        SW_VERSION: "swow"
        COMPOSER_VERSION: "COMPOSER_VERSION_VALUE"
        PHP_BUILD_VERSION: "PHP_BUILD_VERSION_VALUE"

  # dev image
  alpine-dev:
    image: "hyperf/hyperf:8.1-alpine-v3.18-dev"
    build:
      context: "8.1/alpine/dev"
      args:
        ALPINE_VERSION: "3.18"
        COMPOSER_VERSION: "COMPOSER_VERSION_VALUE"
        PHP_BUILD_VERSION: "PHP_BUILD_VERSION_VALUE"
